#!/bin/bash
# This is an example how to use simdemod3_telive --sq5bpf

# This was originally written for telive, but can be used with other software

# note: originally when i write the receiver* scripts they supported gnuradio 3.7 and below.
# these versions did work better for our purposes and had working wxgui which had 
# much better responsiveness. this has been removed, we have to move on to newer versions

# also udp is not the only option. other options (pipes, zmq) have been removed because
# they were rarely used and confused users

read  major minor rest < <( gnuradio-config-info -v | tr '.' ' ' )
version=$((100*$major+$minor))

echo "gnuradio version $version"
if [ "$version" -lt 308 ]; then
echo "gnuradio versions lower than 3.8 are not supported"
exit 1
fi

if [ "$version" -ge 400 ]; then
	# dont allow gnuradio 4.0 just in case. it does not exist yet, but judging by the breakage from 3.7 to 3.8 this is a good idea
	echo "i don't think that gnuradio versions 4.0 and higher are supported, cowardly refusing to run"
	exit 2
fi

# these env variables are used both by simdemod3_telive.py and by tetra-rx
export TETRA_HACK_PORT=7379 #port on which telive listens, i might as well have made this a command line parameter, oh well :)
export TETRA_HACK_IP=127.0.0.1 #ip on which telive listens, you can send to another host too

# receiver identifier from command line parameter, 1 if none given
TETRA_HACK_RXID=1; [ "$1" ] && export TETRA_HACK_RXID=$1
UDP_PORT=$((42000+$TETRA_HACK_RXID))


ulimit -c unlimited

#tetra-rx args: -a turns on pseudo-afc , -i uses an internal float_t_bits
# -r turns on fragment reassembly, -s tries to dump unknown SDS protocols as text
# modify as needed
socat -b 4096 UDP-RECV:${UDP_PORT} STDOUT | demod/simdemod3_telive.py | ./tetra-rx -r -s  /dev/stdin 
